### ISSUE TITLE
I can not get the plugin to work

### ISSUE THREAD

**Issue by marques576** [koslib/terraform-provider-planetscale#10]
![image](https://user-images.githubusercontent.com/23244686/233807386-aa15011b-382b-43aa-a741-9a5f2438ef83.png)
![image](https://user-images.githubusercontent.com/23244686/233807443-3503e3eb-8500-4149-8497-35e9f977efca.png)
![image](https://user-images.githubusercontent.com/23244686/233807457-c226d980-6776-471d-bb64-22dd9ed4d2f5.png)

I have already tried to delete all the cache files of terraform

**Comment by koslib** [comment]
Hi! Could you please post the error message you get?

**Comment by marques576** [comment]
Sorry, but what do you mean by error message. The first image is the error that I get.

**Comment by koslib** [comment]
Sorry, didn't notice the first screenshot! I'm taking a look as soon as possible and will circle back to this!

**Comment by koslib** [comment]
@marques576 a new release is out with a fix for this problem - it's the release version `0.5.1`.

You can reference it like this so that you always get the latest patch version (as you already have based on your screenshot):

```
terraform {
  required_providers {
    planetscale = {
      source  = "registry.terraform.io/koslib/planetscale"
      version = "~> 0.5"
    }
  }
}
```

After that you'll need to upgrade with `terraform init -upgrade`.

Please try this out and let me know if it works for you as well :)

**Comment by koslib** [comment]
I'll be closing this issue for now as it has been verified by other users as fixed - feel free to re-open if the problem persists :)
